import { FieldType, RelationType, defineObject } from 'twenty-sdk/define';

export default defineObject({
  universalIdentifier: '9a00bb7f-f6e5-4703-82bc-0c28d1f606cd',
  nameSingular: 'devisContrat',
  namePlural: 'devisContrats',
  labelSingular: 'Devis / Contrat',
  labelPlural: 'Devis / Contrats',
  icon: 'IconFileText',
  isSearchable: true,
  fields: [
    {
      universalIdentifier: '0cf36693-89f3-4cc8-b3f0-bd3ce6b0776f',
      type: FieldType.TEXT,
      name: 'reference',
      label: 'Référence',
      isNullable: false,
    },
    {
      universalIdentifier: '25437f02-e10f-4ec5-a93a-6b66944c9234',
      type: FieldType.SELECT,
      name: 'typeDocument',
      label: 'Type',
      isNullable: false,
      options: [
        { value: 'DEVIS', label: 'Devis', color: 'blue', position: 0 },
        { value: 'CONTRAT', label: 'Contrat', color: 'green', position: 1 },
        { value: 'AVENANT', label: 'Avenant', color: 'orange', position: 2 },
      ],
    },
    {
      universalIdentifier: '952ba28a-5525-4e1a-80e8-7993ea4a9705',
      type: FieldType.SELECT,
      name: 'typeFacturation',
      label: 'Type de facturation',
      isNullable: false,
      options: [
        { value: 'FORFAIT', label: 'Forfait', color: 'blue', position: 0 },
        { value: 'REGIE', label: 'Régie', color: 'green', position: 1 },
        { value: 'ABONNEMENT', label: 'Abonnement', color: 'purple', position: 2 },
      ],
    },
    {
      universalIdentifier: 'e840b5b3-2ccc-44da-9422-eb77f091cdc5',
      type: FieldType.CURRENCY,
      name: 'montantHt',
      label: 'Montant HT',
      isNullable: false,
      universalSettings: { currencyCode: 'EUR' },
    },
    {
      universalIdentifier: '7b85e433-d1dc-4379-bfa7-2aa4c382b7ad',
      type: FieldType.NUMBER,
      name: 'tauxTva',
      label: 'Taux TVA (%)',
      isNullable: false,
    },
    {
      universalIdentifier: '5a27265f-7682-4a6e-b251-0d62e3b2a5c6',
      type: FieldType.CURRENCY,
      name: 'montantTtc',
      label: 'Montant TTC (calculé)',
      universalSettings: { currencyCode: 'EUR' },
    },
    {
      universalIdentifier: 'b1fbe152-37e0-4391-96f3-e517b889ebf2',
      type: FieldType.SELECT,
      name: 'statut',
      label: 'Statut',
      isNullable: false,
      options: [
        { value: 'BROUILLON', label: 'Brouillon', color: 'gray', position: 0 },
        { value: 'ENVOYE', label: 'Envoyé', color: 'blue', position: 1 },
        { value: 'SIGNE', label: 'Signé', color: 'green', position: 2 },
        { value: 'ANNULE', label: 'Annulé', color: 'red', position: 3 },
      ],
    },
    {
      universalIdentifier: '6f1e149e-13de-45b8-a79c-49c148620262',
      type: FieldType.DATE,
      name: 'dateEmission',
      label: "Date d'émission",
    },
    {
      universalIdentifier: '2f7d49ba-1b00-40c2-9f54-330f4330c7a2',
      type: FieldType.DATE,
      name: 'dateSignature',
      label: 'Date de signature',
    },
    {
      universalIdentifier: 'a025b3b7-3a70-4aa1-a34d-7e4e4cda9acf',
      type: FieldType.NUMBER,
      name: 'version',
      label: 'Version',
    },
    {
      universalIdentifier: 'a1811248-ceec-4d10-a776-e489493fc87a',
      type: FieldType.RICH_TEXT,
      name: 'notes',
      label: 'Notes',
    },
    {
      universalIdentifier: 'add8aa7b-82a0-44c1-a79b-dab3eb3c9e07',
      type: FieldType.RELATION,
      name: 'mission',
      label: 'Mission',
      isNullable: false,
      relationTargetObjectMetadataUniversalIdentifier: '150691d9-e265-4e67-aeaa-a73d7cc6f3e3',
      relationTargetFieldMetadataUniversalIdentifier: 'b94d703b-f988-4c77-9b97-ceed7904a24e',
      universalSettings: { relationType: RelationType.MANY_TO_ONE, joinColumnName: 'missionId' },
    },
    {
      universalIdentifier: '2413b4a4-cdd5-484f-937d-d7755ee900ff',
      type: FieldType.RELATION,
      name: 'client',
      label: 'Client',
      isNullable: false,
      relationTargetObjectMetadataUniversalIdentifier: '63bca1ef-30f3-4df2-8bd8-4cc218eccd31',
      relationTargetFieldMetadataUniversalIdentifier: 'df6ebec4-0129-477d-9e08-9df85b571a91',
      universalSettings: { relationType: RelationType.MANY_TO_ONE, joinColumnName: 'clientId' },
    },
    {
      universalIdentifier: '33271366-5c14-4979-9e3a-90cb22b7689e',
      type: FieldType.RELATION,
      name: 'factures',
      label: 'Factures',
      relationTargetObjectMetadataUniversalIdentifier: '3492ff89-0be2-4a11-9bbb-71b4e3e2c77a',
      relationTargetFieldMetadataUniversalIdentifier: 'a054c84e-9d9c-4862-9eac-5e56cf6548cd',
      universalSettings: { relationType: RelationType.ONE_TO_MANY },
    },
  ],
  labelIdentifierFieldMetadataUniversalIdentifier: '0cf36693-89f3-4cc8-b3f0-bd3ce6b0776f',
});
