import { FieldType, RelationType, defineObject } from 'twenty-sdk/define';

export default defineObject({
  universalIdentifier: '3492ff89-0be2-4a11-9bbb-71b4e3e2c77a',
  nameSingular: 'facture',
  namePlural: 'factures',
  labelSingular: 'Facture',
  labelPlural: 'Factures',
  icon: 'IconReceipt',
  isSearchable: true,
  fields: [
    {
      universalIdentifier: '8cae2f21-9b9b-485f-b6c2-1be3477a98b4',
      type: FieldType.TEXT,
      name: 'numero',
      label: 'Numéro',
      isNullable: false,
    },
    {
      universalIdentifier: 'dd097e00-126b-4d2d-a205-a5248ccb3cb5',
      type: FieldType.SELECT,
      name: 'typeFacture',
      label: 'Type',
      isNullable: false,
      options: [
        { value: 'ACOMPTE', label: 'Acompte', color: 'blue', position: 0 },
        { value: 'INTERMEDIAIRE', label: 'Intermédiaire', color: 'sky', position: 1 },
        { value: 'SOLDE', label: 'Solde', color: 'green', position: 2 },
        { value: 'AVOIR', label: 'Avoir', color: 'orange', position: 3 },
      ],
    },
    {
      universalIdentifier: '55693da0-368d-4727-8dd3-1686724f2352',
      type: FieldType.CURRENCY,
      name: 'montantHt',
      label: 'Montant HT',
      isNullable: false,
      universalSettings: { currencyCode: 'EUR' },
    },
    {
      universalIdentifier: '31f219f4-9cd2-45e8-9844-94888f45370d',
      type: FieldType.NUMBER,
      name: 'tauxTva',
      label: 'Taux TVA (%)',
      isNullable: false,
    },
    {
      universalIdentifier: '573e7614-603a-458d-85a8-13c11c6e5cba',
      type: FieldType.CURRENCY,
      name: 'montantTva',
      label: 'Montant TVA (calculé)',
      universalSettings: { currencyCode: 'EUR' },
    },
    {
      universalIdentifier: '5557a00e-6818-4cc6-8f9e-28b2666cf9f7',
      type: FieldType.CURRENCY,
      name: 'montantTtc',
      label: 'Montant TTC (calculé)',
      universalSettings: { currencyCode: 'EUR' },
    },
    {
      universalIdentifier: '63f8b246-ebd0-4b37-8495-fc89f1f98d67',
      type: FieldType.SELECT,
      name: 'statut',
      label: 'Statut',
      isNullable: false,
      options: [
        { value: 'EMISE', label: 'Émise', color: 'gray', position: 0 },
        { value: 'ENVOYEE', label: 'Envoyée', color: 'blue', position: 1 },
        { value: 'PARTIELLEMENT_PAYEE', label: 'Partiellement payée', color: 'orange', position: 2 },
        { value: 'PAYEE', label: 'Payée', color: 'green', position: 3 },
        { value: 'EN_RETARD', label: 'En retard', color: 'red', position: 4 },
        { value: 'AVOIR', label: 'Avoir', color: 'purple', position: 5 },
      ],
    },
    {
      universalIdentifier: '466cb5ca-1d2a-4114-9102-a700a4158217',
      type: FieldType.DATE,
      name: 'dateEmission',
      label: "Date d'émission",
      isNullable: false,
    },
    {
      universalIdentifier: 'ad0381ad-32a5-4e95-941d-3b1ef584b1ce',
      type: FieldType.DATE,
      name: 'dateEcheance',
      label: "Date d'échéance",
      isNullable: false,
    },
    {
      universalIdentifier: 'bd942f67-1814-451f-84b0-b2bb981b5ce9',
      type: FieldType.DATE,
      name: 'datePaiement',
      label: 'Date de paiement',
    },
    {
      universalIdentifier: 'd889780a-8603-42cb-bf46-d06085c8434e',
      type: FieldType.RICH_TEXT,
      name: 'notes',
      label: 'Notes',
    },
    {
      universalIdentifier: 'a4480afc-a007-45fe-8712-eaaa10d4f17d',
      type: FieldType.RELATION,
      name: 'mission',
      label: 'Mission',
      isNullable: false,
      relationTargetObjectMetadataUniversalIdentifier: '150691d9-e265-4e67-aeaa-a73d7cc6f3e3',
      relationTargetFieldMetadataUniversalIdentifier: '00d71af0-61b9-4fff-a5a9-10ad11340f75',
      universalSettings: { relationType: RelationType.MANY_TO_ONE, joinColumnName: 'missionId' },
    },
    {
      universalIdentifier: '31cdf9e0-d273-419c-9499-d5f1e7d0f75e',
      type: FieldType.RELATION,
      name: 'client',
      label: 'Client',
      isNullable: false,
      relationTargetObjectMetadataUniversalIdentifier: '63bca1ef-30f3-4df2-8bd8-4cc218eccd31',
      relationTargetFieldMetadataUniversalIdentifier: 'b20b34f7-dbd4-4f6e-9ce7-04f1efce5f9b',
      universalSettings: { relationType: RelationType.MANY_TO_ONE, joinColumnName: 'clientId' },
    },
    {
      universalIdentifier: 'a054c84e-9d9c-4862-9eac-5e56cf6548cd',
      type: FieldType.RELATION,
      name: 'devisContrat',
      label: 'Devis / Contrat',
      relationTargetObjectMetadataUniversalIdentifier: '9a00bb7f-f6e5-4703-82bc-0c28d1f606cd',
      relationTargetFieldMetadataUniversalIdentifier: '33271366-5c14-4979-9e3a-90cb22b7689e',
      universalSettings: { relationType: RelationType.MANY_TO_ONE, joinColumnName: 'devisContratId' },
    },
  ],
  labelIdentifierFieldMetadataUniversalIdentifier: '8cae2f21-9b9b-485f-b6c2-1be3477a98b4',
});
